using Content.Client.Humanoid;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.ADT.CharacterFlavor;
using Content.Shared.Humanoid;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.ADT.CharacterFlavor;

[GenerateTypedNameReferences]
public sealed partial class CharacterFlavorWindow : FancyWindow
{
    private readonly IEntityManager _entityManager;
    private readonly IPrototypeManager _proto;
    private readonly IClyde _clyde = default!;
    private EntityUid _character;

    public CharacterFlavorWindow()
    {
        RobustXamlLoader.Load(this);
        _entityManager = IoCManager.Resolve<IEntityManager>();
        _clyde = IoCManager.Resolve<IClyde>();
        _proto = IoCManager.Resolve<IPrototypeManager>();

        HeadshotLoadingLabel.SetMarkup(Loc.GetString("headshot-loading"));
    }

    public void SetEntity(EntityUid uid)
    {
        CharacterView.SetEntity(uid);
        _character = uid;

        if (!_entityManager.TryGetComponent<CharacterFlavorComponent>(_character, out var flavor))
            return;

        if (!_entityManager.TryGetComponent<MetaDataComponent>(uid, out var metaData))
            return;

        if (_entityManager.TryGetComponent<HumanoidAppearanceComponent>(_character, out var humanoid)
        && _proto.Index(humanoid.Species).ShortDesc != string.Empty)
        {
            CustomSpeciesLabel.Text = Loc.GetString(_proto.Index(humanoid.Species).ShortDesc);
            CustomSpeciesTitle.Text = Loc.GetString("flavor-interface-custom-species");
        }

        if (flavor.HeadshotUrl != string.Empty)
        {
            HeadshotImage.TexturePath = "/Textures/_ADT/headshot-loading.png";
            HeadshotLoadingLabel.Visible = true;
        }
        else
        {
            HeadshotContainer.Visible = false;
        }
        Title = metaData.EntityName;
        FlavorTextLabel.Text = flavor.FlavorText;
        OOCNotesLabel.Text = flavor.OOCNotes;
    }
    public void SetHeadshot(byte[] image)
    {
        Logger.Debug("Загрузка ресурсов...");
        var headshot = LoadTextureFromBytes(image);

        if (headshot != null)
        {
            Logger.Debug("Успешная загрузка!");
            HeadshotImage.Texture = headshot;
            HeadshotImage.ModulateSelfOverride = null;
            HeadshotLoadingLabel.Visible = false;
            HeadshotContainer.Visible = true;
        }
        else
        {
            Logger.Debug("Ошибка загрузки текстуры");
            HeadshotContainer.Visible = true;
        }
    }

    private Texture? LoadTextureFromBytes(byte[] imageBytes)
    {
        try
        {
            Logger.Debug("нука нахуй");
            using var memoryStream = new System.IO.MemoryStream(imageBytes);
            using var image = SixLabors.ImageSharp.Image.Load<SixLabors.ImageSharp.PixelFormats.Rgba32>(memoryStream);
            return _clyde.LoadTextureFromImage(image);
        }
        catch
        {
            Logger.Debug("не ка нахуй");
            return null;
        }
    }
}
