// SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
// SPDX-FileCopyrightText: 2023 Morb <14136326+Morb0@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 dffdff2423 <dffdff2423@gmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.FlavorText
{
    [GenerateTypedNameReferences]
    public sealed partial class FlavorText : Control
    {
        public Action<string>? OnFlavorTextChanged;
        public Action<string>? OnOOCNotesChanged;
        public Action<string>? OnHeadshotUrlChanged;
        public FlavorText()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var loc = IoCManager.Resolve<ILocalizationManager>();
            CFlavorTextInput.Placeholder = new Rope.Leaf(loc.GetString("flavor-text-placeholder"));
            CFlavorTextInput.OnTextChanged += _ => FlavorTextChanged();

            // ADT-Tweak-start
            COOCTextInput.OnTextChanged += _ => OOCNotesChanged();
            CHeadshotUrlInput.OnTextChanged += _ => HeadshotUrlChanged();
            // ADT-Tweak-end
        }

        public void FlavorTextChanged()
        {
            OnFlavorTextChanged?.Invoke(Rope.Collapse(CFlavorTextInput.TextRope).Trim());
        }

        // ADT-Tweak-start
        public void OOCNotesChanged()
        {
            OnOOCNotesChanged?.Invoke(Rope.Collapse(COOCTextInput.TextRope).Trim());
        }

        public void HeadshotUrlChanged()
        {
            OnHeadshotUrlChanged?.Invoke(CHeadshotUrlInput.Text.Trim());
        }
        // ADT-Tweak-end
    }
}
