
- type: gameMapPool
  id: DefaultMapPool
  maps:
  # Highpop 55+
  - CorvaxAstra
  #- CorvaxAvrite
  - CorvaxBox
  - CorvaxChloris
  #- CorvaxDelta
  - CorvaxGlacier
  - CorvaxPilgrim

  # Midpop 25–55
  # - CorvaxAmber
  - CorvaxAwesome
  - CorvaxBagel
  #- CorvaxMarathon
  - CorvaxMascara
  - CorvaxOutpost
  - CorvaxPaper
  #- CorvaxPearl
  - CorvaxVoid

  # Lowpop 0–25
  - CorvaxMaus
  - FreakyOmega # Freaky
  - FreakySaltern # Freaky
  - CorvaxPacked
  # - CorvaxSilly
  - MiniSilly
  - CorvaxTushkan
  - CorvaxCluster
